customhost = "employee.cnc8v934xnb0.us-west-2.rds.amazonaws.com"
customuser = "dbadmin"
custompass = "Baseball%2021"
customdb = "employee"
custombucket = "addeemployee"
customregion = "us-west-2"
customtable = "employee"
